---
title: "Reproducible Research: Peer Assessment 1"
output: 
  html_document:
    keep_md: true
---


### Loading and preprocessing the data
```{r load and preprocess, message=FALSE, warning=FALSE}
unzip("activity.zip")
data <- read.csv("activity.csv")
```

### What is mean total number of steps taken per day?
```{r total number of steps, message=FALSE, warning=FALSE}
library(dplyr)
library(ggplot2)

df_date <- summarize(na.omit(data) %>% group_by(date), steps = sum(steps))

qplot(date, steps, data = df_date, stat = "identity", geom = "histogram") +
    geom_histogram(binwidth = 10) +
    theme(axis.text.x = element_text(angle = 90, hjust = 1, vjust = 0.5, size = 5)) +
    xlab("observation dates") +
    ylab("total steps") +
    labs(title = "missing values removed")

avg <- mean(df_date$steps)
print(paste("the mean is ", avg))

med <- median(df_date$steps)
print(paste("the median is ", med))

```

### What is the average daily activity pattern?
```{r average steps, message=FALSE, warning=FALSE}
library(dplyr)
library(ggplot2)
df_interval <- summarize(na.omit(data) %>% group_by(interval), steps = mean(steps))

qplot(interval, steps, data = df_interval, geom = "line") +
    scale_x_continuous(breaks = seq(0, 3000, by = 100)) +
    scale_y_continuous(breaks = seq(0, 250, by = 25)) +
    theme(axis.text.x = element_text(angle = 30, hjust = 0.5, vjust = 0.5)) +
    xlab("time interval") +
    ylab("average steps") +
    labs(title = "average daily activity")

x <- df_interval[which.max(df_interval$steps),]
sprintf("The 5 minute interval %.0f has the max average number of steps %f", 
        x$interval, x$steps)
```

### Imputing missing values
#### number of missing values
```{r missing values, message=FALSE, warning=FALSE}
sumNA <- sum(is.na(data$steps))
sprintf("Number of missing values %.0f", sumNA)

```
#### use interval mean of primary data set to address NA values
```{r supply missing values, message=FALSE, warning=FALSE, echo=FALSE}
library(dplyr)
library(ggplot2)

# NA rows 
data_NA <- filter(data, is.na(steps))
data_noNA <- filter(data, !is.na(steps))
data_NA$steps <- NULL

# add steps column with mean steps previously calculated
df2 <- inner_join(data_NA, df_interval)

# re-arrange columns in preparation of rbind
df2 <- df2[c(3, 1, 2)]

# row bind
df <- rbind(data_noNA, df2)

# re-calculate total steps per day
df_date <- summarize(df %>% group_by(date), steps = sum(steps))

qplot(date, steps, data = df_date, stat = "identity", geom = "histogram") +
    geom_histogram(binwidth = 10) +
    theme(axis.text.x = element_text(angle = 90, hjust = 1, vjust = 0.5, size = 5)) +
    xlab("observation dates") +
    ylab("total steps") +
    labs(title = "imputed missing values")

avg <- mean(df_date$steps)
print(paste("the mean with imputed missing values is ", avg))

med <- median(df_date$steps)
print(paste("the median with imputed missing values is ", med))

```

### Are there differences in activity patterns between weekdays and weekends?
```{r weekday vs weekend activity patterns, message=FALSE, warning=FALSE}

# add day of week as factor
df$dayofweek <- as.factor(weekdays(as.Date(df$date)))
z <- ifelse(df$dayofweek %in% c("Saturday", "Sunday"), "Weekend", "Weekday")
df <- cbind(df, z)

# rollup weekday/weekend, interval
df_rollup <- summarize(df %>% group_by(z, interval), steps = mean(steps))

ggplot(df_rollup, aes(interval, steps)) + 
    geom_line() + 
    facet_wrap(~ z, ncol = 1) +
    xlab("5-minute interval") + 
    ylab("Number of steps")
```

